[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
log = "^0.4"
env_logger = "^0.11"
mio = { version = "^1.0", features = ["os-poll", "os-ext", "net"] }
tun = "^0.6"
