[package]
name = "server"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
common = { workspace = true }
tun = { workspace = true }
mio = { workspace = true }
clap = { version = "4.5.*", features = ["cargo", "color", "derive"] }

# data
chrono = { workspace = true }
serde = { workspace = true}
etherparse = { workspace = true }

# logging
log = { workspace = true }
tracing-subscriber = { workspace = true }
tracing = { workspace = true }
tracing-appender = { workspace = true }