[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
env_logger = "0.11.5"
tokio = { version = "1.40.0", features = ["rt", "rt-multi-thread", "macros"] }
tun = "^0.6"