[workspace]
resolver = "2"
members = [
    "src/client",
    "src/server",
    "src/shared"
]

[workspace.package]
edition = "2021"

[workspace.dependencies]
shared = { path = "src/shared" }

# data
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
etherparse = "0.17"

# logging
tracing = "0.1"
tracing-subscriber = "0.3"
tracing-appender = "0.2"
