[workspace]
resolver = "2"
members = [
    "crates/cli",
    "crates/sdk",
]

[workspace.package]
version = "0.5.0"
edition = "2024"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1

[profile.bench]
inherits = "release"
debug = true

[workspace.dependencies]
# io
tokio = { version = "1.47", features = ["rt", "rt-multi-thread", "macros", "sync", "time", "socket2"] }
tun-rs = { version = "2.8.8", features = ["async_tokio"] }
ctrlc = "3.4"
anstyle = "1.0"
clap = "4.5"

# data
bytes = { version = "1.11", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
bincode = { version = "2.0", features = ["serde"] }
base64 = "0.22"
toml = "0.8"
thiserror = "2.0"

# logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"
