identifier = "com.holynet.vpn"

[build]
dev-url = "http://localhost:5173"
#frontendDist = "client"

[bundle]
active = true
icon = ["icons/logo.svg"]

[[app.windows]]
title = "Holynet VPN"
fullscreen = false
resizable = true
height = 950
width = 550
minWidth = 550
minHeight = 950
maxWidth = 900
maxHeight = 1200

[plugins.updater]
pubkey = "updater pub key"
endpoints = ["https://my.app.updater/{{target}}/{{current_version}}"]