[package]
name = "holynet-sdk"
version.workspace = true
edition.workspace = true

[features]
default = ["client", "server", "udp-reuse-port"]
client = []
server = []

# transport features
udp = ["socket2"]
udp-reuse-port = ["udp"]
ws = ["socket2", "tokio-tungstenite", "futures", "dashmap"]
ws-reuse-port = ["ws"]


[dependencies]
snow = "0.10"

# > IO
tokio = { version = "1.47", features = ["rt", "macros", "sync", "time", "socket2"] }
tracing = "0.1"
async-trait = "0.1"
# transport
socket2 = { version = "0.6", optional = true }
tokio-tungstenite = { version = "0.28", optional = true }
futures = { version = "0.3", optional = true }
dashmap = { version = "7.0.0-rc2", optional = true }

# > Other
serde = { version = "1.0", features = ["derive"] }
bincode = "2.0"
base64 = "0.22"