[package]
name = "holynet-sdk"
version.workspace = true
edition.workspace = true

[features]
default = ["udp-reuse-port"]

# transport features
udp = ["socket2"]
udp-reuse-port = ["udp"]
ws = ["socket2", "tokio-tungstenite"]
ws-reuse-port = ["ws"]


[dependencies]
snow = "0.10"

# > IO
tokio = { workspace = true }
tun-rs = { workspace = true }
tracing = { workspace = true }

# transport
socket2 = { version = "0.6", optional = true }
tokio-tungstenite = { version = "0.28", optional = true }
# > sessions / concurrency
dashmap = "6"
rand = "0.9"
rand_core = { version = "0.6", features = ["getrandom"] }

# > network
pnet = "0.35"

# > crypto
x25519-dalek = { version = "2.0", features = ["static_secrets"] }

# > Other
bytes = { workspace = true }
serde = { workspace = true }
bincode = { workspace = true }
base64 = { workspace = true }
anyhow = { workspace = true }
futures = "0.3"
