[package]
name = "shared"
version = "0.1.0"
edition.workspace = true

[dependencies]
sunbeam =  { workspace = true}
serde = { version = "1.0.217", features = ["derive"] }
base64 = "0.22.1"
toml = "0.8.19"
bincode = "1.3.*"
