[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "^0.4"
tokio = { version = "1.40.0", features = ["rt", "rt-multi-thread", "macros"] }
tun = "^0.6"
bincode = "^1.3"
serde = { version = "1.0.210", features = ["derive"] }
env_logger = "0.11.5"
