name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build client
      run: cargo build --verbose --package client --bin client-cli --feature cli

    - name: Build server
      run: cargo build --verbose --package server --bin server

    - name: Run client tests
      run: cargo test --verbose --package client

    - name: Run server tests
      run: cargo test --verbose --package server
